### ISSUE TITLE
Undefined symbol in MinGW DEBUG build with 3.0a2

### ISSUE THREAD

**Issue by yoerg** [modelon-community/fmi-library#80]
Build 3.0a2 as a _MinGW Makefiles_ project with
````bat
cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Debug ../fmi-library-3.0a2
cmake --build .
````
results in an error when linking `jm_locale_test`:
````
[....]
[ 55%] Linking C executable jm_locale_test.exe
C:/..../x86_64-w64-mingw32/bin/ld.exe: CMakeFiles\jm_locale_test.dir/objects.a(jm_locale_test.c.obj): in function `test_parse_with_locale':
C:/..../fmi-library-build/fmi-library-3.0a2/Test/jm_locale_test.c:39: undefined reference to `__imp_jm_get_default_callbacks'
collect2.exe: error: ld returned 1 exit status
````

Building with `-DCMAKE_BUILD_TYPE=Release` completes without errors. The 3.0a1 _DEBUG_ build completes without errors, as does skipping the tests with `-DFMILIB_BUILD_TESTS=0`.

````
cmake version 3.26.4
gcc (MinGW-W64 x86_64-ucrt-mcf-seh, built by Brecht Sanders) 13.1.0
````

**Comment by PeterMeisrimelModelon** [comment]
Thanks for reporting this and being very thorough in testing the alpha releases. We'll look into fixing this for the next alpha or beta release.
